spring:
  application:
    name: budget

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: username
    password: password

